=== vladyslav-sereda/projects/done/SummaryTask3/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--  XML schema -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://SummaryTask3.sereda.nure.ua/"
            xmlns:tns="http://SummaryTask3.sereda.nure.ua/">

    <xsd:element name="Cards">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="OldCard" type="tns:OldCard" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="OldCard">
        <xsd:sequence>
            <xsd:element name="Thema" type="xsd:string"/>
            <xsd:element name="Type" type="tns:Type"/>
            <xsd:element name="Country" type="xsd:string"/>
            <xsd:element name="Year" type="xsd:gYear"/>
            <xsd:element name="Author" type="xsd:Name" minOccurs="0"/>
            <xsd:element name="Valuable" type="tns:Valuable"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Type">
        <xsd:all>
            <xsd:element name="TypeName" type="tns:TypeName"/>
        </xsd:all>
        <xsd:attribute name="Send" type="xsd:boolean" default="false"/>
    </xsd:complexType>

    <xsd:simpleType name="TypeName">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Congratulatory"/>
            <xsd:enumeration value="Advertising"/>
            <xsd:enumeration value="Normal"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="Valuable">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Historical"/>
            <xsd:enumeration value="Thematic"/>
            <xsd:enumeration value="Collection"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== vladyslav-sereda/projects/done/SummaryTask3/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="stylesheetForXml.xsl" type="text/xsl"?>
<!--  Input XML document. This XML is valid against Test.xsd XML schema-->

<st3:Cards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:st3="http://SummaryTask3.sereda.nure.ua/"
         xsi:schemaLocation="http://SummaryTask3.sereda.nure.ua/ input.xsd">

    <OldCard>
        <Thema>Mountains</Thema>
        <Type Send = "false">
            <TypeName>Normal</TypeName>
        </Type>
        <Country>Ukraine</Country>
        <Year>1973</Year>
        <Author>Balashov</Author>
        <Valuable>Historical</Valuable>
    </OldCard>

    <OldCard>
        <Thema>Exposition</Thema>
        <Type Send="true">
            <TypeName>Advertising</TypeName>
        </Type>
        <Country>Germany</Country>
        <Year>2001</Year>
        <Valuable>Thematic</Valuable>
    </OldCard>

    <OldCard>
        <Thema>People</Thema>
        <Type Send = "true">
            <TypeName>Normal</TypeName>
        </Type>
        <Country>USA</Country>
        <Year>2018</Year>
        <Author>Sereda</Author>
        <Valuable>Collection</Valuable>
    </OldCard>

</st3:Cards>
